ARG VERSION=3.1-alpine

FROM mcr.microsoft.com/dotnet/core/sdk:$VERSION as build

WORKDIR /src
ADD . .

RUN dotnet restore ./CommunAxiomWeb.csproj

#NodeJS
RUN apk update
RUN apk add --update nodejs-current npm

RUN dotnet publish ./CommunAxiomWeb.csproj -c Release -o ./publish

FROM mcr.microsoft.com/dotnet/core/aspnet:$VERSION

EXPOSE 443

WORKDIR /app

RUN apk update
RUN apk add --no-cache --update ca-certificates
RUN rm -rf /var/cache/apk/*

COPY --from=build src/publish ./

RUN chown 1000: ./
RUN chmod -R u+x ./

USER 1000

ENTRYPOINT ["dotnet", "/app/CommunAxiomWeb.dll"]